# Form implementation generated from reading ui file 'lib_game.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 30, 211, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 80, 111, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 140, 91, 21))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 140, 61, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuMAd = QtWidgets.QMenu(self.menubar)
        self.menuMAd.setObjectName("menuMAd")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuMAd.addSeparator()
        self.menubar.addAction(self.menuMAd.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.game)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Mad Libs Generator</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Have Fun!</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Click Here:</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.menuMAd.setTitle(_translate("MainWindow", "Mad Libs Generator"))


    def game(self):
        print("Today I went to the zoo. I saw a(n) _ _ jumping up and down in its tree."
            "He _ _ through the large tunnel that led to its _ _ I got some peanuts and passed them through the cage to a gigantic gray _ towering above my head."
            "Feeding that animal made me hungry. I went to get a _ scoop of ice cream. It filled my stomach."
            "Afterwards I had to _ _ to catch our bus. When I got home I _ my mom for a _ day at the zoo.")

        w1 = str(input('adjective: '))
        w2 = str(input('noun: '))
        w3 = str(input('verb: '))
        w4 = str(input('adverb: '))
        w5 = str(input('adjective: '))
        w6 = str(input('noun: '))
        w7 = str(input('noun: '))
        w8 = str(input('adjective: '))
        w9 = str(input('verb: '))
        w10 = str(input('adverb: '))
        w11 = str(input('verb: '))
        w12 = str(input('adjective: '))

        print("Today I went to the zoo. I saw a(n)" + w1 + w2 + "jumping up and down in its tree."
            "He" + w3 + w4 + "through the large tunnel that led to its" + w5 + w6 + "I got some peanuts and passed them through the cage to a gigantic gray" + w7 + "towering above my head."
            "Feeding that animal made me hungry. I went to get a" + w8 + "scoop of ice cream. It filled my stomach."
            "Afterwards I had to" + w9 + w10 + "to catch our bus. When I got home I" + w11 + "my mom for a" + w12 + "day at the zoo.")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
